spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 1234
    url: jdbc:mysql://localhost:3306/meet
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
      
  jackson:
    serialization:
     INDENT_OUTPUT: true
  mvc:
    servlet:
      path: /meet-api
    
app:
  api:
    name: Recursos Unpaz
    version: v1.0.0
  http:
    auth-token-header: API-KEY
    auth-token-header-value: 123hdj12-772b-4e4b-943d-41jhsk38fk

